### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mac1202** [sananth12/ImageScraper#34]
for every url i try i got the same error : 
Traceback (most recent call last):
  File "/usr/bin/image-scraper", line 9, in <module>
    load_entry_point('ImageScraper==2.0.5', 'console_scripts', 'image-scraper')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/image_scraper/__init__.py", line 10
    print "\nImageScraper\n============\nRequesting page....\n"
                                                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by srirams6** [comment]
You are using python3. This module isn't completely supported on python3 yet. Please use python2.7.

**Comment by mac1202** [comment]
ok i ve installed pip2.7 and reinstall imagescraper now i got anaother error : 
ImageScraper
============
Requesting page....

Found 18 images:
Traceback (most recent call last):                                                                                              | ETA:  --:--:--   0.00 B/s
  File "/usr/bin/image-scraper", line 9, in <module>
    load_entry_point('ImageScraper==2.0.5', 'console_scripts', 'image-scraper')()
  File "/usr/lib/python2.7/site-packages/image_scraper/__init__.py", line 37, in console_main
    flag, size_flag = download_image(img_url, download_path, max_filesize)
  File "/usr/lib/python2.7/site-packages/image_scraper/utils.py", line 107, in download_image
    f = open(os.path.join(download_path,  img_url.split('/')[-1]), 'w')
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

**Comment by sananth12** [comment]
Fixed it. @mac1202  Please build ImageScraper again form source. Thanks!
