### ISSUE TITLE
Possible Improvement: Warn if not connected to internet.

### ISSUE THREAD

**Issue by rw1018** [sananth12/ImageScraper#86]
I received this error after running image-scraper. I didn't realize at the time my computer was disconnected from the wifi. 

It might be worthwhile to throw a warning if the program cannot reach the internet.

Traceback (most recent call last):
  File "C:\Users\Ronald\Code\image-scrapper\env\Scripts\image-scraper-script.py", line 9, in <module>
    load_entry_point('ImageScraper==2.0.7', 'console_scripts', 'image-scraper')()
  File "build\bdist.win32\egg\image_scraper\mains.py", line 21, in console_main
  File "build\bdist.win32\egg\image_scraper\utils.py", line 115, in get_html
UnboundLocalError: local variable 'page' referenced before assignment

**Comment by sananth12** [comment]
@rw1018 Seems like a good idea. I will add the warning. Thanks!

**Comment by ssundarraj** [comment]
@sananth12 I'll get working on this and send a PR.

**Comment by sananth12** [comment]
@rw1018 feature added! 
@ssundarraj  thanks!
